name: Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:

  check-php-syntax:
    name: PHP ${{ matrix.php-version }} Syntax
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.1"
          - "8.4"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          fail-on-warnings: true

  php-coding-style:
    name: Check PHP coding style
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: php-cs-fixer:v3
          coverage: none
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check PHP coding style
        run: |
          php-cs-fixer fix --path-mode=intersection --config=.php-cs-fixer.dist.php --dry-run --diff --using-cache=no --no-interaction --ansi .

  phpunit:
    name: PHPUnit
    needs:
      - check-php-syntax
      - php-coding-style
    env:
      CODE_COVERAGE_TOOL: none
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        composer-flags:
          - "--prefer-lowest"
          - "--prefer-stable"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set code coverage
        if: startsWith(matrix.os, 'ubuntu') && matrix.php-version == '7.4'
        run: |
          echo "CODE_COVERAGE_TOOL=xdebug" >> $GITHUB_ENV
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: ${{ env.CODE_COVERAGE_TOOL }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Composer dependencies ${{ matrix.composer-flags }}
        run: composer --ansi --no-interaction --no-progress --optimize-autoloader ${{ matrix.composer-flags }} update
      - name: Run PHPUnit (without code coverage)
        if: ${{ env.CODE_COVERAGE_TOOL == 'none' }}
        run: composer --ansi --no-interaction run-script test
      - name: Run PHPUnit (with code coverage)
        if: ${{ env.CODE_COVERAGE_TOOL != 'none' }}
        run: composer --ansi --no-interaction run-script test -- --coverage-clover coverage-clover.xml
      - name: Download Coveralls
        if: ${{ env.CODE_COVERAGE_TOOL != 'none' }}
        run: curl -sSLf -o php-coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar
      - name: Upload Coveralls data
        if: ${{ env.CODE_COVERAGE_TOOL != 'none' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          php php-coveralls.phar
          --coverage_clover=coverage-clover.xml --json_path=coveralls-upload.json --ansi --no-interaction -vvv
      - name: Download Scrutinizer
        if: ${{ env.CODE_COVERAGE_TOOL != 'none' }}
        run: curl -sSLf -o ocular.phar https://scrutinizer-ci.com/ocular.phar
      - name: Upload Scrutinizer data
        if: ${{ env.CODE_COVERAGE_TOOL != 'none' }}
        run: >
          php ocular.phar code-coverage:upload
          --format=php-clover --ansi --no-interaction
          coverage-clover.xml
